import { readFileSync } from 'node:fs';
const d = JSON.parse(readFileSync('data/products.json', 'utf8')).products;
console.log('material=Other:', d.filter((p) => p.material === 'Other').length);
const show = (label, rows) => { console.log(`\n${label}:`); for (const p of rows) console.log(`  ${p.material} / ${p.colour} [${(p.colours || []).join('+')}] / ${p.finish || '-'} | ${p.name.slice(0, 60)}`); };
show('Silk 3dea (was Other)', d.filter((p) => p.store === '3dea' && /^silk/i.test(p.name)).slice(0, 6));
show('PAHT-CF / PPA-CF', d.filter((p) => /^(PAHT|PPA)-CF$/.test(p.material)));
show('eMarble / Wood (pbtech/marvle)', d.filter((p) => /emarble|eSun Wood/i.test(p.name)).slice(0, 4));
show('PEEK / PEI / PPS / PEBA / PVC / PVA-aquatek / PVB-polycast', d.filter((p) => /^(PEEK|PEI|PPS|PSU|PEBA|PVC|PVA|PVB)$/.test(p.material)).slice(0, 10));
console.log('\nMulti with components:', d.filter((p) => (p.colours || []).length > 2).length, 'products');
const mats = {};
for (const p of d) mats[p.material] = (mats[p.material] || 0) + 1;
console.log('\nmaterials:', Object.entries(mats).sort((a, b) => b[1] - a[1]).slice(0, 30));
